language: node_js
sudo: false

node_js:
- '6'

os:
- linux

## Disable because it seems to be often slow (and sometimes errored)
## on Travis CI
# - osx

matrix:
  fast_finish: true
  exclude:
  - os: osx
    node_js: '4'

script:
- npm test

branches:
  only:
  - master
  - /^greenkeeper/.*$/

### cache node_modules/ dir between builds on travis
# Issues with node 4
#cache:
#  directories:
#    - node_modules

deploy:
  provider: npm
  email: lgreco@mozilla.com
  skip_cleanup: true
  on:
    tags: true
    repo: rpl/flow-coverage-report
  api_key:
    secure: C57mp1All3XfB6o4g6ws9zXTPmdOcIBCca+9652PgLqXEhYc8q8H7j7Wwg5erQxNaUjNvU3Pb8a9t3xgLBNUybXwmvdSM0N/hPr3svhepP6npeC0KXhk35C3tRMukZ1XGfHvxjAJydoxhpDTfMqzlUnIDe4G9rBNa8ye5QgtAxBrUE1L/A52wnmLUdM2xyEti7gPP87aax1vK8kkA31Cp+DeGm5j+meA762Wa5FThahNJGBE92JU5yM0VbVXRU+kui2p8/LMCvXv/1UqzZVMlb4Irj3tPXSgje2dMKjA+4d+soNyu/cXtBWeL0ac6NM7LUUsFgSaZ6roURBrveR+eGh5VeL0QrVsIer+4ha1lGf5WwIfAC8ExwbjUlsWrd9dRjhUSl6TU/zsFUH1VPk2spj6z+7/RAUj9pyZ1Dhy01MZaSbnIEIgJhmE5kvd9+0N06ezoGiFfij1CyHnnqG5GIbpaBnm+p6BABhouGnQ7VMzlotehgfnNo5xOEPB9+E9v/xCm4D94sH3/30CNKizBRxXBN8KCHLmZ66KcQXzNPDVh2ONm3oZd+FvfevQM+7NIwRQsIzNxc0mVvJ3MsUE9Y1A/7/zm7cuREOgokmj5qwP1T08xwEVPXREpGVugi0cHPYaakIJ6bcsAG2uptKk9Fzk5HkMWKEZMGFNpc4Od7Y=
